allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  "@dnd-kit/abstract": 0.3.2
  "@dnd-kit/dom": 0.3.2
peerDependencyRules:
  allowedVersions:
    "@waveform-playlist/annotations@12.0.6>react": "19"
